export const weaponTypes = [
  {
    name: "Gun",
    sizeCost: 3,
    baseCost: 0,
    sizeUse: 1,
    baseUse: 2,
    sizeRange: 4,
    baseRange: 2,
    damage: "d6",
    damageMulSize: true,
    usePower: true,
    notes: "-"
  },
  {
    name: "Blast Gun",
    sizeCost: 3,
    baseCost: 0,
    sizeUse: 1,
    baseUse: 1,
    sizeRange: 2,
    baseRange: 2,
    damage: "d8 - (distance)",
    damageMulSize: true,
    usePower: true,
    notes: "1 Firing Arc, no Auto Penalty, Target size modifiers affect Damage"
  },
  {
    name: "Machine Gun",
    sizeCost: 4,
    baseCost: 0,
    sizeUse: 1,
    baseUse: 2,
    sizeRange: 3,
    baseRange: 2,
    damage: "d6",
    damageMulSize: true,
    usePower: true,
    notes: "-1 Auto Penalty per Arc or Burst, may require Reload"
  },
  {
    name: "Flame Thrower",
    sizeCost: 3,
    baseCost: 0,
    sizeUse: 1,
    baseUse: 1,
    sizeRange: 2,
    baseRange: 2,
    damage: "d4 Fire",
    damageMulSize: true,
    usePower: true,
    notes: "min. 1 Firing Arc, -1 Auto Penalty per Arc, Target size modifiers affect Damage"
  },
  {
    name: "Cannon",
    sizeCost: 3,
    baseCost: 0,
    sizeUse: 1,
    baseUse: 3,
    sizeRange: 4,
    baseRange: 0,
    damage: "(determined by Ammunition)",
    damageMulSize: false,
    usePower: true,
    notes: "requires Reload after each shot, max ammunition Explosive Size of ? (Size)\""
  },
  {
    name: "Launcher",
    sizeCost: 3,
    baseCost: 0,
    sizeUse: 2,
    baseUse: 0,
    sizeRange: 6,
    baseRange: 0,
    damage: "(determined by payload)",
    damageMulSize: false,
    usePower: true,
    notes: "max Payload Size of ? (Size)\", max Explosive Size of (Size) bricks"
  },
  {
    name: "Melee Weapon",
    sizeCost: 2,
    baseCost: 0,
    sizeUse: 1,
    baseUse: 1,
    sizeRange: 0,
    baseRange: "CC",
    damage: "Skill die",
    damageMulSize: true,
    usePower: true,
    notes: "-"
  },
  {
    name: "Melee Shield",
    sizeCost: 1,
    baseCost: 0,
    sizeUse: 2,
    baseUse: 0,
    sizeRange: 0,
    baseRange: "CC",
    damage: "x Shielded Parry",
    damageMulSize: true,
    usePower: true,
    notes: "Parry or Shove only, can Parry Charge attacks"
  }
] 