export const weaponTypes = [
  {
    name: "Gun",
    category: "Weapon",
    sizeCost: 3,
    baseCost: 0,
    sizeUse: 1,
    baseUse: 2,
    sizeRange: 4,
    baseRange: 2,
    damage: "d6",
    damageMulSize: true,
    usePower: true,
    notes: "-"
  },
  {
    name: "Blast Gun",
    category: "Weapon",
    sizeCost: 3,
    baseCost: 0,
    sizeUse: 1,
    baseUse: 1,
    sizeRange: 2,
    baseRange: 2,
    damage: "d8 - (distance)",
    damageMulSize: true,
    usePower: true,
    notes: "1 Firing Arc, no Auto Penalty, Target size modifiers affect Damage"
  },
  {
    name: "Machine Gun",
    category: "Weapon",
    sizeCost: 4,
    baseCost: 0,
    sizeUse: 1,
    baseUse: 2,
    sizeRange: 3,
    baseRange: 2,
    damage: "d6",
    damageMulSize: true,
    usePower: true,
    notes: "-1 Auto Penalty per Arc or Burst, may require Reload"
  },
  {
    name: "Flame Thrower",
    category: "Weapon",
    sizeCost: 3,
    baseCost: 0,
    sizeUse: 1,
    baseUse: 1,
    sizeRange: 2,
    baseRange: 2,
    damage: "d4 Fire",
    damageMulSize: true,
    usePower: true,
    notes: "min. 1 Firing Arc, -1 Auto Penalty per Arc, Target size modifiers affect Damage"
  },
  {
    name: "Cannon",
    category: "Weapon",
    sizeCost: 3,
    baseCost: 0,
    sizeUse: 1,
    baseUse: 3,
    sizeRange: 4,
    baseRange: 0,
    damage: "(determined by Ammunition)",
    damageMulSize: false,
    usePower: true,
    notes: "requires Reload after each shot, max ammunition Explosive Size of ? (Size)\""
  },
  {
    name: "Launcher",
    category: "Weapon",
    sizeCost: 3,
    baseCost: 0,
    sizeUse: 2,
    baseUse: 0,
    sizeRange: 6,
    baseRange: 0,
    damage: "(determined by payload)",
    damageMulSize: false,
    usePower: true,
    notes: "max Payload Size of ? (Size)\", max Explosive Size of (Size) bricks"
  },
  {
    name: "Melee Weapon",
    category: "Weapon",
    sizeCost: 2,
    baseCost: 0,
    sizeUse: 1,
    baseUse: 1,
    sizeRange: 0,
    baseRange: "CC",
    damage: "Skill die",
    damageMulSize: true,
    usePower: true,
    notes: "-"
  },
  {
    name: "Melee Shield",
    category: "Weapon",
    sizeCost: 1,
    baseCost: 0,
    sizeUse: 2,
    baseUse: 0,
    sizeRange: 0,
    baseRange: "CC",
    damage: "x Shielded Parry",
    damageMulSize: true,
    usePower: true,
    notes: "Parry or Shove only, can Parry Charge attacks"
  },
  {
    name: "Tool",
    category: "Weapon",
    sizeCost: 1,
    baseCost: 0,
    sizeUse: 0,
    baseUse: 3,
    sizeRange: 0,
    baseRange: "CC",
    damage: "Skill die - ",
    damageMulSize: true,
    damageAddSize: true,
    usePower: true,
    notes: "-"
  },
  {
    name: "Explosive",
    category: "Explosive",
    sizeCost: 1,
    baseCost: 0,
    sizeUse: 0,
    baseUse: 2,
    sizeRange: 0,
    baseRange: "CC or 3''",
    damage: "d10 Explosion",
    damageMulSize: true,
    usePower: false,
    notes: "ranged stats can be determined by Launcher or Cannon, if any"
  },
  {
    name: "Incendiary Explosive",
    category: "Explosive",
    sizeCost: 1,
    baseCost: 0,
    sizeUse: 0,
    baseUse: 2,
    sizeRange: 0,
    baseRange: "CC or 3''",
    damage: "d4 Fire",
    damageMulSize: true,
    usePower: false,
    notes: "ranged stats can be determined by Launcher or Cannon, if any"
  },
  {
    name: "Armor Piercing Explosive",
    category: "Explosive",
    sizeCost: 1,
    baseCost: 0,
    sizeUse: 0,
    baseUse: 2,
    sizeRange: 0,
    baseRange: "CC or 3''",
    damage: "d6 Pierce",
    damageMulSize: true,
    usePower: false,
    notes: "ranged stats can be determined by Launcher or Cannon, if any"
  },
  {
    name: "Concussion Explosive",
    category: "Explosive",
    sizeCost: 1,
    baseCost: 0,
    sizeUse: 0,
    baseUse: 2,
    sizeRange: 0,
    baseRange: "CC or 3''",
    damage: "d8 Knockback",
    damageMulSize: true,
    usePower: false,
    notes: "ranged stats can be determined by Launcher or Cannon, if any"
  },
  {
    name: "Phased Explosive",
    category: "Explosive",
    sizeCost: 1,
    baseCost: 0,
    sizeUse: 0,
    baseUse: 2,
    sizeRange: 0,
    baseRange: "CC or 3''",
    damage: "d10 (2d10 = d12 Phased)",
    damageMulSize: true,
    usePower: false,
    notes: "Costs two d10's to use each d12"
  },
  {
    name: "Rocket",
    category: "Explosive",
    sizeCost: 2,
    baseCost: 0,
    sizeUse: 2,
    baseUse: 0,
    sizeRange: 6,
    baseRange: 0,
    damage: "d10 Explosion",
    damageMulSize: true,
    usePower: true,
    notes: "-"
  },
  {
    name: "Long-Ranged Weapon",
    category: "Bastard",
    sizeCost: 0,
    baseCost: 5,
    sizeUse: 0,
    baseUse: 3,
    sizeRange: 0,
    baseRange: 10,
    damage: "1d6 + 1",
    damageMulSize: false,
    usePower: true,
    forMinifigs: true,
    size: 1.5,
    notes: "-"
  },
  {
    name: "ShotGun",
    category: "Bastard",
    sizeCost: 0,
    baseCost: 4,
    sizeUse: 0,
    baseUse: 3,
    sizeRange: 0,
    baseRange: 6,
    damage: "1d8 + 1 - (distance)",
    damageMulSize: false,
    usePower: true,
    forMinifigs: true,
    size: 1.5,
    notes: "1 Firing Arc, no Auto Penalty, Target Size modifiers affect Damage, 1\" KnockBack to minifigs or smaller"
  },
  {
    name: "AutoGun",
    category: "Bastard",
    sizeCost: 0,
    baseCost: 6,
    sizeUse: 0,
    baseUse: 3,
    sizeRange: 0,
    baseRange: 8,
    damage: "1d6 + 1",
    damageMulSize: false,
    usePower: true,
    forMinifigs: true,
    size: 1.5,
    notes: "-1 Auto Penalty per Arc or Burst, may require Reload"
  },
  {
    name: "FlameGun",
    category: "Bastard",
    sizeCost: 0,
    baseCost: 4,
    sizeUse: 0,
    baseUse: 2,
    sizeRange: 0,
    baseRange: 5,
    damage: "1d4 + 1 Fire",
    damageMulSize: false,
    usePower: true,
    forMinifigs: true,
    size: 1.5,
    notes: "min 1 Firing Arc, -1 Auto Penalty per Arc, Target Size modifiers affect Damage"
  },
  {
    name: "Bazooka",
    category: "Bastard",
    sizeCost: 0,
    baseCost: 4,
    sizeUse: 0,
    baseUse: 3,
    sizeRange: 0,
    baseRange: 6,
    damage: "(determined by Ammunition)",
    damageMulSize: false,
    usePower: true,
    forMinifigs: true,
    size: 1.5,
    notes: "requires reload after each shot, max Explosive Size (XS) of 1"
  },
  {
    name: "RailGun",
    category: "Bastard",
    sizeCost: 0,
    baseCost: 4,
    sizeUse: 0,
    baseUse: 3,
    sizeRange: 0,
    baseRange: 8,
    damage: "(determined by Payload)",
    damageMulSize: false,
    usePower: true,
    forMinifigs: true,
    size: 1.5,
    notes: "max Payload Size of 1\", max Explosive Size (XS) of 2"
  },
  {
    name: "Heavy Weapon",
    category: "Bastard",
    sizeCost: 0,
    baseCost: 3,
    sizeUse: 0,
    baseUse: 3,
    sizeRange: 0,
    baseRange: "CC",
    damage: "Skill die + 2",
    damageMulSize: false,
    usePower: true,
    forMinifigs: true,
    size: 1.5,
    notes: "may be paired with Shield or Heavy Shield, 1\" KnockBack to minifigs (no Disruption)"
  },
  {
    name: "Two-Handed Weapon",
    category: "Bastard",
    sizeCost: 0,
    baseCost: 4,
    sizeUse: 0,
    baseUse: 4,
    sizeRange: 0,
    baseRange: "CC",
    damage: "2 Skill dice",
    damageMulSize: false,
    usePower: true,
    forMinifigs: true,
    size: 2,
    notes: "Two-Handed; -1\" Move; can't Sprint; can't throw;1\" KnockBack to minifigs"
  },
  {
    name: "Heavy Shield",
    category: "Bastard",
    sizeCost: 0,
    baseCost: 1,
    sizeUse: 0,
    baseUse: 3,
    sizeRange: 0,
    baseRange: "CC",
    damage: "Shielded Parry",
    damageMulSize: false,
    usePower: true,
    forMinifigs: true,
    size: 1.5,
    notes: "Parry or Shove only, can Parry Charge attacks, can provide cover"
  },
  {
    name: "Wand",
    category: "Bastard",
    sizeCost: 0,
    baseCost: 0,
    sizeUse: 0,
    baseUse: 2,
    sizeRange: 0,
    baseRange: "CC or 6''",
    damage: "-",
    damageMulSize: false,
    usePower: true,
    forMinifigs: true,
    size: 1,
    notes: "extends the reach of SuperNatural Effects by touch, melee attack, or ranged attack"
  },
  {
    name: "Staff",
    category: "Bastard",
    sizeCost: 0,
    baseCost: 0,
    sizeUse: 0,
    baseUse: 3,
    sizeRange: 0,
    baseRange: "CC or 10''",
    damage: "-",
    damageMulSize: false,
    usePower: true,
    forMinifigs: true,
    size: 2,
    notes: "extends the reach of SuperNatural Effects by touch, melee attack, or ranged attack"
  }
]; 